-- GameShelf: definição das tabelas

CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS games(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    release_year INTEGER,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    rating INTEGER
);

CREATE TABLE IF NOT EXISTS shelf_items(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'wishlist',
    rating INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, game_id),
    CHECK(status IN ('wishlist', 'playing', 'completed', 'dropped')),
    CHECK(rating IS NULL OR (rating >= 1 AND rating <= 10))
);

INSERT INTO games(title, platform, release_year) VALUES
('The Legend of Zelda: Breath of the Wild', 'Nintendo Switch', 2017),
('The Witcher 3: Wild Hunt', 'PlayStation 4', 2015),
('The Last of Us Part II', 'PlayStation 4', 2020),
('The Elder Scrolls V: Skyrim', 'PlayStation 4', 2011);

INSERT INTO shelf_items(user_id, game_id, status, rating) VALUES
(1,1,'completed', 9);


SELECT * FROM shelf_items;

SELECT title, platform
FROM games
WHERE platform = 'PC';


SELECT
    users.email,
    games.title,
    shelf_items.status,
    shelf_items.rating
FROM shelf_items
JOIN users ON users.id = shelf_items.user_id
JOIN games ON games.id = shelf_items.game_id;


UPDATE shelf_items
SET status = 'playing', rating = NULL
WHERE id = 1;

SELECT id, status, rating FROM shelf_items WHERE id = 1;

DELETE FROM games WHERE title = 'Celeste';
